name: "Terraform Valida Modulo"

on: workflow_dispatch

jobs:
  terraform: 
    uses: "mentoriaiac/cicd_centralizado/.github/workflows/terraform_valida_modulo.yaml@main"
    with:
      working_directory: "./instance" 
