name: "Terraform Executa Modulo"

on: workflow_dispatch
  
jobs:
  terraform:
    uses: "Guerlielton/cicd_centralizado/.github/workflows/terraform.yaml@feat/terraform-download-private-modules"
    with:
      plan: true
      apply: true
      workspace: "default"
    secrets: inherit
#     secrets:
#       GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }} 
